name: Test

on:
  push:
  workflow_dispatch:

env:
  APP_NAME: "IWA-Java [KAL]"
  RELEASE_NAME: "main"

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: release-id-or-name
        shell: bash
        run: |
           echo "release = ${FOD_RELEASE}"
           case ${FOD_RELEASE} in
             ''|*[!0-9]*) echo '_RELEASE_OPT=--fod.release.name='''${FOD_RELEASE}''' >> $GITHUB_ENV ;;
             *) echo '_RELEASE_OPT="--fod.release.id=${FOD_RELEASE}"' >> $GITHUB_ENV ;;
           esac
        env:
          #FOD_RELEASE: ${{ format('{0}:{1}', env.APP_NAME, env.RELEASE_NAME) }}
          FOD_RELEASE: 'IWA-Java [KAL]: main'
          #FOD_RELEASE: 12345
      - name: echo-release-opt
        shell: bash
        run: |
          echo ${_RELEASE_OPT}
        env:
          FOD_RELEASE: ${{ format('{0}:{1}', env.APP_NAME, env.RELEASE_NAME) }}
      - uses: kadraman/gha-test/internal/run@main
        with:
          cmd: 'echo FoDToGitHub "--fod.baseUrl=${FOD_URL}" "--fod.tenant=${FOD_TENANT}" "--fod.user=${FOD_USER}" "--fod.password=${FOD_PASSWORD}" "--fod.clientID=${FOD_CLIENT_ID}" "--fod.clientSecret=${FOD_CLIENT_SECRET}" "''${_RELEASE_OPT}''"'

