name: Test

on:
  push:
  workflow_dispatch:

env:
  APP_NAME: "IWA-Java [KAL]"
  RELEASE_NAME: "main"

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
       uses: actions/checkout@v3.3.0
      -name: release-id-or-name
       shell: bash
       run: |
           case ${FOD_RELEASE} in
             ''|*[!0-9]*) echo '_RELEASE_OPT="--fod.release.name=${FOD_RELEASE}"' >> $GITHUB_ENV ;;
            *) echo '_RELEASE_OPT="--fod.release.id=${FOD_RELEASE}"' >> $GITHUB_ENV ;;
        esac
       env:
         FOD_RELEASE: ${{ format('{0}:{1}', env.APP_NAME, env.RELEASE_NAME) }}
